PREFIX exb: <http://exmaralda.org/en/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?token ?topic
where{ ?tok a exb:tok. 
       ?tok rdfs:label ?token.
       ?tok exb:start/exb:time ?t.
       BIND(xsd:double(?t) as ?time)
       OPTIONAL { 
         ?top a exb:TOPIC.
         ?top exb:start/exb:time ?sTop.
         ?top exb:end/exb:time ?eTop.
         FILTER(xsd:double(?sTop)<=?time)
         FILTER(xsd:double(?eTop)>?time)
         ?top rdfs:label ?topic
         }
     } ORDER BY ?time